## Wprowadzenie

In [3]:
a = 3 + 4
a + 10

17

In [4]:
a

7

In [6]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### Importuyjemy numpy

In [8]:
import numpy as np

In [11]:
a = [1,2,3,4,5] * 100000
len(a)

500000

In [16]:
b = np.array(a)
len(b)

500000

In [17]:
b

array([1, 2, 3, ..., 3, 4, 5])

In [18]:
b + 10

array([11, 12, 13, ..., 13, 14, 15])

In [27]:
%%timeit -n1 -r10
[i ** 2 for i in a]

129 ms ± 6.2 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)


In [33]:
%%timeit -n1 -r10
b ** 2

1.07 ms ± 135 µs per loop (mean ± std. dev. of 10 runs, 1 loop each)


In [40]:
c = np.array([[1, 2], [3, 4], [5, 6]])
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
c.shape

(3, 2)

In [38]:
c.size

6

In [44]:
d = np.arange(5, 10, .4)
d

array([5. , 5.4, 5.8, 6.2, 6.6, 7. , 7.4, 7.8, 8.2, 8.6, 9. , 9.4, 9.8])

In [47]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
np.ones(4)

array([1., 1., 1., 1.])

In [49]:
np.linspace(1, 2, 4)

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [51]:
def fun(x, y):
    return 10*x + y

np.fromfunction(fun, (5, 5))

array([[ 0.,  1.,  2.,  3.,  4.],
       [10., 11., 12., 13., 14.],
       [20., 21., 22., 23., 24.],
       [30., 31., 32., 33., 34.],
       [40., 41., 42., 43., 44.]])

In [59]:
tab = np.arange(20)
tab = tab.reshape((4, 5))
tab

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

### Wycinanie

In [66]:
t = np.arange(10)
t[2:4] += 10
t

array([ 0,  1, 12, 13,  4,  5,  6,  7,  8,  9])

In [69]:
tab

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [71]:
tab[1:3, 3:] = 0
tab

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  0,  0],
       [10, 11, 12,  0,  0],
       [15, 16, 17, 18, 19]])